"""add role and real name to user

Revision ID: 004
Revises: 003
Create Date: 2026-04-30

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删除 is_superuser 列，添加新列
    op.add_column('users', sa.Column('real_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('super_admin', 'operator', 'developer', 'auditor', name='userrole'), nullable=False, server_default='operator'))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))

    # 把原来的 is_superuser=True 的用户升级为 super_admin
    op.execute("UPDATE users SET role = 'super_admin' WHERE is_superuser = 1")

    # 删除旧的 is_superuser 列
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True, server_default=sa.text('0')))

    # 把 super_admin 降级为 is_superuser=True
    op.execute("UPDATE users SET is_superuser = 1 WHERE role = 'super_admin'")

    op.drop_column('users', 'created_by')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'real_name')
    # ### end Alembic commands ###
